id: P003279
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD89998
  title: དཀར་མཛེས་རྫོང་གི་ལོ་རྒྱུས་མཐུད་བསྒྲིགས།
  author: ''
  volumes:
    d3920b669bc541af915d80822733e09a:
      image_group_id: I1PD90049
      title: ''
      volume_number: 1
      total_pages: 534
      base_file: v001.txt
