id: I44A27F88
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:05:02+00:00'
last_modified: '2022-06-07T18:49:01.059469+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD89998
  title: དཀར་མཛེས་རྫོང་གི་ལོ་རྒྱུས་མཐུད་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6143':
      image_group_id: I1PD90049
      title: ''
      total_pages: 534
      order: 1
      base_file: 6143.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
